# Generated by Django 5.0.6 on 2024-06-11 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_recruiterprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='seekerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('resume', models.FileField(upload_to='static/resume')),
                ('myuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SeekerProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
