# Generated by Django 5.0.6 on 2024-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_customuser_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(default='None', null=True, upload_to='static/resume'),
        ),
    ]
