# Generated by Django 5.0.6 on 2024-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_customuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
